target 'ReduxTest' do
# Uncomment this line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!

# Pods for ReduxTest
pod 'Firebase/Messaging'

target 'ReduxTestTests' do
inherit! :search_paths
# Pods for testing
end

end
